### PR TITLE
assignment 3

### PR DESCRIPTION
**Pull request by ydong6**
I think i was submit it wrong yesterday night, so i just resubmit it.
Thanks.

### CODE REVIEW

**Comment by brantfaircloth** [comment]
This is not quite correct - you only want to add the ```answers/ydong6/README.md``` file and not modify the main README.md file.

**Comment by brantfaircloth** [comment]
I uploaded your file for you (this time).  We'll go over this process in class once again tomorrow.

**Comment by ydong6** [comment]
Sorry Dr Faircloth, I was so confused, but I think I figured out by now.
Thank you for your help.
Yuankai

Sent from Outlook Mobile<https://aka.ms/qtex0l>

_____________________________

**Comment by brantfaircloth** [comment]
On 27 Jan 2016, at 9:31, Yuankai Dong wrote:

> Sorry Dr Faircloth, I was so confused, but I think I figured out by now.
> Thank you for your help.

it’s no problem, Yuankai - we’ll go over this a bit tomorrow.

see you then,
b

**Pull request closed without merging**
